"""Create the authoritative PostgreSQL/pgvector schema.

Revision ID: 0001_initial_schema
Revises:
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None

JSONB = postgresql.JSONB
TEXT_ARRAY = postgresql.ARRAY(sa.String(64))
INT_ARRAY = postgresql.ARRAY(sa.Integer)
TS = sa.DateTime(timezone=True)


def _json_object() -> sa.Column:
    return sa.Column("payload", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb"))


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "actors",
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("kind", sa.String(16), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("public_background", sa.Text(), nullable=False),
        sa.Column("public_impression", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.PrimaryKeyConstraint("actor_id", name="pk_actors"),
        sa.CheckConstraint("kind IN ('player', 'npc')", name="ck_actors_kind"),
    )
    op.create_table(
        "npc_profiles",
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("persona_summary", sa.Text(), nullable=False),
        sa.Column("traits", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("values", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("social_style", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("speech_style", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("boundaries", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("core_secrets", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.actor_id"], ondelete="CASCADE", name="fk_npc_profiles_actor"),
        sa.PrimaryKeyConstraint("actor_id", name="pk_npc_profiles"),
    )
    op.create_table(
        "topics",
        sa.Column("topic_id", sa.String(64), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("aliases", JSONB, nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.PrimaryKeyConstraint("topic_id", name="pk_topics"),
        sa.UniqueConstraint("name", name="uq_topics_name"),
    )
    op.create_table(
        "goal_definitions",
        sa.Column("goal_id", sa.String(64), nullable=False),
        sa.Column("owner_npc_id", sa.String(64), nullable=False),
        sa.Column("horizon", sa.String(32), nullable=False),
        sa.Column("disclosure", sa.String(32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("importance", sa.SmallInteger(), nullable=False),
        sa.Column("target_actor_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("topic_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("initial_status", sa.String(32), nullable=False, server_default=sa.text("'active'")),
        sa.ForeignKeyConstraint(["owner_npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_goal_definitions_owner"),
        sa.PrimaryKeyConstraint("goal_id", name="pk_goal_definitions"),
        sa.CheckConstraint("importance BETWEEN 1 AND 5", name="ck_goal_definitions_importance"),
        sa.CheckConstraint("horizon IN ('short_term', 'long_term', 'chapter')", name="ck_goal_definitions_horizon"),
        sa.CheckConstraint("disclosure IN ('shareable', 'guarded')", name="ck_goal_definitions_disclosure"),
    )
    op.create_table(
        "agendas",
        sa.Column("agenda_id", sa.String(64), nullable=False),
        sa.Column("chapter_id", sa.String(128), nullable=False),
        sa.Column("owner_npc_id", sa.String(64), nullable=False),
        sa.Column("public_goal_id", sa.String(64), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("public_summary", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["owner_npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_agendas_owner"),
        sa.ForeignKeyConstraint(["public_goal_id"], ["goal_definitions.goal_id"], ondelete="RESTRICT", name="fk_agendas_public_goal"),
        sa.PrimaryKeyConstraint("agenda_id", name="pk_agendas"),
        sa.UniqueConstraint("chapter_id", "title", name="uq_agendas_chapter_title"),
    )
    op.create_table(
        "chapter_runs",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("chapter_id", sa.String(128), nullable=False),
        sa.Column("scenario_revision", sa.String(128), nullable=False, server_default=sa.text("'scenario-v1'")),
        sa.Column("player_agenda_id", sa.String(64), nullable=True),
        sa.Column("world_day", sa.SmallInteger(), nullable=False, server_default=sa.text("1")),
        sa.Column("world_minute", sa.SmallInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("clock_status", sa.String(32), nullable=False, server_default=sa.text("'running'")),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("event_seq", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("next_conversation_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("next_segment_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("next_message_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("next_invitation_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("next_join_request_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("next_memory_seq", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("daily_think_order", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("public_world_state", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("scene_state", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("zhou_authorization", sa.String(32), nullable=False, server_default=sa.text("'none'")),
        sa.Column("chapter_resolution", JSONB, nullable=True),
        sa.Column("run_finished", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("closed_days", INT_ARRAY, nullable=False, server_default=sa.text("'{}'::integer[]")),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["player_agenda_id"], ["agendas.agenda_id"], ondelete="RESTRICT", name="fk_chapter_runs_player_agenda"),
        sa.PrimaryKeyConstraint("run_id", name="pk_chapter_runs"),
        sa.CheckConstraint("world_day BETWEEN 1 AND 7", name="ck_chapter_runs_world_day"),
        sa.CheckConstraint("world_minute BETWEEN 0 AND 1439", name="ck_chapter_runs_world_minute"),
        sa.CheckConstraint("clock_status IN ('running', 'paused', 'chapter_ended')", name="ck_chapter_runs_clock_status"),
        sa.CheckConstraint("zhou_authorization IN ('none', 'approved', 'conditional', 'rejected')", name="ck_chapter_runs_zhou_authorization"),
        sa.CheckConstraint("state_version >= 0", name="ck_chapter_runs_state_version"),
        sa.CheckConstraint("event_seq >= 0", name="ck_chapter_runs_event_seq"),
        sa.CheckConstraint("next_conversation_seq >= 0 AND next_segment_seq >= 0 AND next_message_seq >= 0 AND next_invitation_seq >= 0 AND next_join_request_seq >= 0 AND next_memory_seq >= 0", name="ck_chapter_runs_next_sequences"),
    )
    op.create_table(
        "run_actor_states",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("external_status", sa.String(32), nullable=False, server_default=sa.text("'present'")),
        sa.Column("position_x", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("position_y", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("daily_think_minute", sa.SmallInteger(), nullable=True),
        sa.Column("thought_days", INT_ARRAY, nullable=False, server_default=sa.text("'{}'::integer[]")),
        sa.Column("actor_world_state", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("fresh_event_memory_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_run_actor_states_run"),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_run_actor_states_actor"),
        sa.PrimaryKeyConstraint("run_id", "actor_id", name="pk_run_actor_states"),
        sa.CheckConstraint("external_status IN ('present', 'approaching', 'inviting', 'chatting', 'waiting', 'departed')", name="ck_run_actor_states_external_status"),
        sa.CheckConstraint("daily_think_minute IS NULL OR daily_think_minute BETWEEN 0 AND 1439", name="ck_run_actor_states_daily_think_minute"),
    )
    op.create_table(
        "run_daily_schedules",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("world_day", sa.SmallInteger(), nullable=False),
        sa.Column("npc_id", sa.String(64), nullable=False),
        sa.Column("slot_minute", sa.SmallInteger(), nullable=False),
        sa.Column("slot_order", sa.SmallInteger(), nullable=False),
        sa.Column("thought_status", sa.String(32), nullable=False, server_default=sa.text("'scheduled'")),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("started_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("finished_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_run_daily_schedules_run"),
        sa.ForeignKeyConstraint(["npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_run_daily_schedules_npc"),
        sa.PrimaryKeyConstraint("run_id", "world_day", "npc_id", name="pk_run_daily_schedules"),
        sa.UniqueConstraint("run_id", "world_day", "slot_minute", name="uq_run_daily_schedules_slot"),
        sa.CheckConstraint("world_day BETWEEN 1 AND 7", name="ck_run_daily_schedules_world_day"),
        sa.CheckConstraint("slot_minute BETWEEN 0 AND 1439", name="ck_run_daily_schedules_slot_minute"),
        sa.CheckConstraint("slot_order >= 0", name="ck_run_daily_schedules_slot_order"),
        sa.CheckConstraint("thought_status IN ('scheduled', 'started', 'completed', 'skipped')", name="ck_run_daily_schedules_thought_status"),
    )
    op.create_table(
        "run_events",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("event_seq", sa.BigInteger(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(128), nullable=False),
        sa.Column("payload", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("world_day", sa.SmallInteger(), nullable=False),
        sa.Column("world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_run_events_run"),
        sa.PrimaryKeyConstraint("run_id", "event_seq", name="pk_run_events"),
        sa.CheckConstraint("event_seq >= 0", name="ck_run_events_event_seq"),
        sa.CheckConstraint("state_version >= 0", name="ck_run_events_state_version"),
        sa.CheckConstraint("world_day BETWEEN 1 AND 7", name="ck_run_events_world_day"),
        sa.CheckConstraint("world_minute BETWEEN 0 AND 1439", name="ck_run_events_world_minute"),
    )
    op.create_table(
        "command_records",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("command_id", sa.String(128), nullable=False),
        sa.Column("fingerprint", sa.String(128), nullable=False),
        sa.Column("result", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_command_records_run"),
        sa.PrimaryKeyConstraint("run_id", "command_id", name="pk_command_records"),
        sa.UniqueConstraint("run_id", "fingerprint", name="uq_command_records_fingerprint"),
    )
    op.create_table(
        "world_events",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("event_id", sa.String(64), nullable=False),
        sa.Column("world_day", sa.SmallInteger(), nullable=False),
        sa.Column("world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("event_kind", sa.String(64), nullable=False),
        sa.Column("source_label", sa.String(200), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("topic_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("visible_actor_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("neutral_payload", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_world_events_run"),
        sa.PrimaryKeyConstraint("run_id", "event_id", name="pk_world_events"),
        sa.CheckConstraint("world_day BETWEEN 1 AND 7", name="ck_world_events_world_day"),
        sa.CheckConstraint("world_minute BETWEEN 0 AND 1439", name="ck_world_events_world_minute"),
    )
    op.create_table(
        "world_event_observers",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("event_id", sa.String(64), nullable=False),
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("observed_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("observed_world_minute", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(["run_id", "event_id"], ["world_events.run_id", "world_events.event_id"], ondelete="CASCADE", name="fk_world_event_observers_event"),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_world_event_observers_actor"),
        sa.PrimaryKeyConstraint("run_id", "event_id", "actor_id", name="pk_world_event_observers"),
        sa.CheckConstraint("observed_world_day BETWEEN 1 AND 7", name="ck_world_event_observers_day"),
        sa.CheckConstraint("observed_world_minute BETWEEN 0 AND 1439", name="ck_world_event_observers_minute"),
    )
    op.create_table(
        "topic_candidates",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("candidate_id", sa.String(64), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.String(200), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("first_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("first_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("last_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("last_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'candidate'")),
        sa.Column("promoted_topic_id", sa.String(64), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_topic_candidates_run"),
        sa.ForeignKeyConstraint(["promoted_topic_id"], ["topics.topic_id"], ondelete="SET NULL", name="fk_topic_candidates_topic"),
        sa.PrimaryKeyConstraint("run_id", "candidate_id", name="pk_topic_candidates"),
        sa.UniqueConstraint("run_id", "normalized_text", name="uq_topic_candidates_normalized"),
        sa.CheckConstraint("mention_count > 0", name="ck_topic_candidates_mention_count"),
        sa.CheckConstraint("status IN ('candidate', 'promoted', 'discarded')", name="ck_topic_candidates_status"),
        sa.CheckConstraint("first_world_day BETWEEN 1 AND 7 AND last_world_day BETWEEN 1 AND 7", name="ck_topic_candidates_days"),
        sa.CheckConstraint("first_world_minute BETWEEN 0 AND 1439 AND last_world_minute BETWEEN 0 AND 1439", name="ck_topic_candidates_minutes"),
    )
    op.create_table(
        "conversations",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("conversation_seq", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'open'")),
        sa.Column("close_reason", sa.String(64), nullable=True),
        sa.Column("contains_player", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("started_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("started_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("ended_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("ended_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_conversations_run"),
        sa.PrimaryKeyConstraint("run_id", "conversation_id", name="pk_conversations"),
        sa.UniqueConstraint("run_id", "conversation_seq", name="uq_conversations_sequence"),
        sa.CheckConstraint("conversation_seq > 0", name="ck_conversations_sequence"),
        sa.CheckConstraint("status IN ('open', 'closed')", name="ck_conversations_status"),
        sa.CheckConstraint("started_world_day BETWEEN 1 AND 7", name="ck_conversations_started_day"),
        sa.CheckConstraint("started_world_minute BETWEEN 0 AND 1439", name="ck_conversations_started_minute"),
        sa.CheckConstraint("ended_world_day IS NULL OR ended_world_day BETWEEN 1 AND 7", name="ck_conversations_ended_day"),
        sa.CheckConstraint("ended_world_minute IS NULL OR ended_world_minute BETWEEN 0 AND 1439", name="ck_conversations_ended_minute"),
    )
    op.create_table(
        "conversation_participants",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("joined_seq", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("joined_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("joined_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("left_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("left_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_conversation_participants_conversation"),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_conversation_participants_actor"),
        sa.PrimaryKeyConstraint("run_id", "conversation_id", "actor_id", name="pk_conversation_participants"),
        sa.CheckConstraint("joined_seq > 0", name="ck_conversation_participants_joined_seq"),
        sa.CheckConstraint("joined_world_day BETWEEN 1 AND 7", name="ck_conversation_participants_joined_day"),
        sa.CheckConstraint("joined_world_minute BETWEEN 0 AND 1439", name="ck_conversation_participants_joined_minute"),
        sa.CheckConstraint("left_world_day IS NULL OR left_world_day BETWEEN 1 AND 7", name="ck_conversation_participants_left_day"),
        sa.CheckConstraint("left_world_minute IS NULL OR left_world_minute BETWEEN 0 AND 1439", name="ck_conversation_participants_left_minute"),
    )
    op.create_table(
        "conversation_segments",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("segment_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("segment_seq", sa.Integer(), nullable=False),
        sa.Column("started_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("started_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("ended_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("ended_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("participant_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("summary", JSONB, nullable=True),
        sa.Column("summary_through_message_id", sa.String(64), nullable=True),
        sa.Column("summary_status", sa.String(32), nullable=False, server_default=sa.text("'none'")),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_conversation_segments_conversation"),
        sa.PrimaryKeyConstraint("run_id", "segment_id", name="pk_conversation_segments"),
        sa.UniqueConstraint("run_id", "conversation_id", "segment_seq", name="uq_conversation_segments_seq"),
        sa.CheckConstraint("segment_seq > 0", name="ck_conversation_segments_seq"),
        sa.CheckConstraint("started_world_day BETWEEN 1 AND 7", name="ck_conversation_segments_started_day"),
        sa.CheckConstraint("started_world_minute BETWEEN 0 AND 1439", name="ck_conversation_segments_started_minute"),
        sa.CheckConstraint("ended_world_day IS NULL OR ended_world_day BETWEEN 1 AND 7", name="ck_conversation_segments_ended_day"),
        sa.CheckConstraint("ended_world_minute IS NULL OR ended_world_minute BETWEEN 0 AND 1439", name="ck_conversation_segments_ended_minute"),
        sa.CheckConstraint("summary_status IN ('none', 'pending', 'succeeded', 'failed')", name="ck_conversation_segments_summary_status"),
    )
    op.create_table(
        "segment_participants",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("segment_id", sa.String(64), nullable=False),
        sa.Column("actor_id", sa.String(64), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("joined_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("joined_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("left_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("left_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id", "segment_id"], ["conversation_segments.run_id", "conversation_segments.segment_id"], ondelete="CASCADE", name="fk_segment_participants_segment"),
        sa.ForeignKeyConstraint(["actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_segment_participants_actor"),
        sa.PrimaryKeyConstraint("run_id", "segment_id", "actor_id", name="pk_segment_participants"),
        sa.CheckConstraint("joined_world_day BETWEEN 1 AND 7", name="ck_segment_participants_joined_day"),
        sa.CheckConstraint("joined_world_minute BETWEEN 0 AND 1439", name="ck_segment_participants_joined_minute"),
        sa.CheckConstraint("left_world_day IS NULL OR left_world_day BETWEEN 1 AND 7", name="ck_segment_participants_left_day"),
        sa.CheckConstraint("left_world_minute IS NULL OR left_world_minute BETWEEN 0 AND 1439", name="ck_segment_participants_left_minute"),
    )
    op.create_table(
        "messages",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("message_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("segment_id", sa.String(64), nullable=False),
        sa.Column("message_seq", sa.Integer(), nullable=False),
        sa.Column("author_actor_id", sa.String(64), nullable=False),
        sa.Column("message_kind", sa.String(32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("visible_to_npc_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("world_day", sa.SmallInteger(), nullable=False),
        sa.Column("world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_messages_conversation"),
        sa.ForeignKeyConstraint(["run_id", "segment_id"], ["conversation_segments.run_id", "conversation_segments.segment_id"], ondelete="CASCADE", name="fk_messages_segment"),
        sa.ForeignKeyConstraint(["author_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_messages_author"),
        sa.PrimaryKeyConstraint("run_id", "message_id", name="pk_messages"),
        sa.UniqueConstraint("run_id", "conversation_id", "message_seq", name="uq_messages_sequence"),
        sa.CheckConstraint("message_seq > 0", name="ck_messages_sequence"),
        sa.CheckConstraint("message_kind IN ('player', 'npc', 'system')", name="ck_messages_kind"),
        sa.CheckConstraint("world_day BETWEEN 1 AND 7", name="ck_messages_world_day"),
        sa.CheckConstraint("world_minute BETWEEN 0 AND 1439", name="ck_messages_world_minute"),
    )
    op.create_table(
        "conversation_idle_states",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("idle_count", sa.SmallInteger(), nullable=False, server_default=sa.text("0")),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("last_idle_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("last_idle_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_conversation_idle_states_conversation"),
        sa.PrimaryKeyConstraint("run_id", "conversation_id", name="pk_conversation_idle_states"),
        sa.CheckConstraint("idle_count >= 0", name="ck_conversation_idle_states_count"),
        sa.CheckConstraint("last_idle_world_day IS NULL OR last_idle_world_day BETWEEN 1 AND 7", name="ck_conversation_idle_states_day"),
        sa.CheckConstraint("last_idle_world_minute IS NULL OR last_idle_world_minute BETWEEN 0 AND 1439", name="ck_conversation_idle_states_minute"),
    )
    op.create_table(
        "goals",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("goal_id", sa.String(64), nullable=False),
        sa.Column("definition_goal_id", sa.String(64), nullable=True),
        sa.Column("parent_goal_id", sa.String(64), nullable=True),
        sa.Column("owner_npc_id", sa.String(64), nullable=False),
        sa.Column("horizon", sa.String(32), nullable=False),
        sa.Column("disclosure", sa.String(32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("importance", sa.SmallInteger(), nullable=False),
        sa.Column("target_actor_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("topic_ids", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'active'")),
        sa.Column("created_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("created_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("resolved_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("resolved_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("resolution_reason", sa.String(128), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_goals_run"),
        sa.ForeignKeyConstraint(["definition_goal_id"], ["goal_definitions.goal_id"], ondelete="RESTRICT", name="fk_goals_definition"),
        sa.ForeignKeyConstraint(["run_id", "parent_goal_id"], ["goals.run_id", "goals.goal_id"], ondelete="RESTRICT", name="fk_goals_parent"),
        sa.ForeignKeyConstraint(["owner_npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_goals_owner"),
        sa.PrimaryKeyConstraint("run_id", "goal_id", name="pk_goals"),
        sa.CheckConstraint("importance BETWEEN 1 AND 5", name="ck_goals_importance"),
        sa.CheckConstraint("horizon IN ('short_term', 'long_term', 'chapter')", name="ck_goals_horizon"),
        sa.CheckConstraint("disclosure IN ('shareable', 'guarded')", name="ck_goals_disclosure"),
        sa.CheckConstraint("status IN ('active', 'blocked', 'completed', 'abandoned', 'departed')", name="ck_goals_status"),
        sa.CheckConstraint("created_world_day BETWEEN 1 AND 7", name="ck_goals_created_day"),
        sa.CheckConstraint("created_world_minute BETWEEN 0 AND 1439", name="ck_goals_created_minute"),
        sa.CheckConstraint("resolved_world_day IS NULL OR resolved_world_day BETWEEN 1 AND 7", name="ck_goals_resolved_day"),
        sa.CheckConstraint("resolved_world_minute IS NULL OR resolved_world_minute BETWEEN 0 AND 1439", name="ck_goals_resolved_minute"),
    )
    op.create_table(
        "relationships",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("from_actor_id", sa.String(64), nullable=False),
        sa.Column("to_actor_id", sa.String(64), nullable=False),
        sa.Column("social_roles", TEXT_ARRAY, nullable=False, server_default=sa.text("'{}'::text[]")),
        sa.Column("familiarity", sa.Float(), nullable=False, server_default=sa.text("0")),
        sa.Column("trust", sa.Float(), nullable=False, server_default=sa.text("0")),
        sa.Column("affinity", sa.Float(), nullable=False, server_default=sa.text("0")),
        sa.Column("tension", sa.Float(), nullable=False, server_default=sa.text("0")),
        sa.Column("interaction_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("updated_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("updated_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_relationships_run"),
        sa.ForeignKeyConstraint(["from_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_relationships_from_actor"),
        sa.ForeignKeyConstraint(["to_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_relationships_to_actor"),
        sa.PrimaryKeyConstraint("run_id", "from_actor_id", "to_actor_id", name="pk_relationships"),
        sa.CheckConstraint("from_actor_id <> to_actor_id", name="ck_relationships_distinct_actors"),
        sa.CheckConstraint("familiarity BETWEEN 0 AND 3", name="ck_relationships_familiarity"),
        sa.CheckConstraint("trust BETWEEN -2 AND 2", name="ck_relationships_trust"),
        sa.CheckConstraint("affinity BETWEEN -2 AND 2", name="ck_relationships_affinity"),
        sa.CheckConstraint("tension BETWEEN 0 AND 2", name="ck_relationships_tension"),
        sa.CheckConstraint("interaction_count >= 0", name="ck_relationships_interaction_count"),
        sa.CheckConstraint("updated_world_day IS NULL OR updated_world_day BETWEEN 1 AND 7", name="ck_relationships_updated_day"),
        sa.CheckConstraint("updated_world_minute IS NULL OR updated_world_minute BETWEEN 0 AND 1439", name="ck_relationships_updated_minute"),
    )
    op.create_table(
        "invitations",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("invitation_id", sa.String(64), nullable=False),
        sa.Column("invitation_seq", sa.Integer(), nullable=False),
        sa.Column("initiator_actor_id", sa.String(64), nullable=False),
        sa.Column("target_actor_id", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("conversation_id", sa.String(64), nullable=True),
        sa.Column("private_goal_id", sa.String(64), nullable=True),
        sa.Column("private_payload", JSONB, nullable=True),
        sa.Column("requested_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("requested_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("responded_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("responded_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_invitations_run"),
        sa.ForeignKeyConstraint(["initiator_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_invitations_initiator"),
        sa.ForeignKeyConstraint(["target_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_invitations_target"),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="RESTRICT", name="fk_invitations_conversation"),
        sa.ForeignKeyConstraint(["run_id", "private_goal_id"], ["goals.run_id", "goals.goal_id"], ondelete="RESTRICT", name="fk_invitations_private_goal"),
        sa.PrimaryKeyConstraint("run_id", "invitation_id", name="pk_invitations"),
        sa.UniqueConstraint("run_id", "invitation_seq", name="uq_invitations_sequence"),
        sa.CheckConstraint("invitation_seq > 0", name="ck_invitations_sequence"),
        sa.CheckConstraint("initiator_actor_id <> target_actor_id", name="ck_invitations_distinct_actors"),
        sa.CheckConstraint("status IN ('pending', 'accepted', 'refused', 'expired')", name="ck_invitations_status"),
        sa.CheckConstraint("requested_world_day BETWEEN 1 AND 7", name="ck_invitations_requested_day"),
        sa.CheckConstraint("requested_world_minute BETWEEN 0 AND 1439", name="ck_invitations_requested_minute"),
        sa.CheckConstraint("responded_world_day IS NULL OR responded_world_day BETWEEN 1 AND 7", name="ck_invitations_responded_day"),
        sa.CheckConstraint("responded_world_minute IS NULL OR responded_world_minute BETWEEN 0 AND 1439", name="ck_invitations_responded_minute"),
    )
    op.create_table(
        "join_requests",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("join_request_id", sa.String(64), nullable=False),
        sa.Column("join_request_seq", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("applicant_actor_id", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("requested_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("requested_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("resolved_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("resolved_world_minute", sa.SmallInteger(), nullable=True),
        sa.Column("resolution_reason", sa.String(64), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["chapter_runs.run_id"], ondelete="CASCADE", name="fk_join_requests_run"),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_join_requests_conversation"),
        sa.ForeignKeyConstraint(["applicant_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_join_requests_applicant"),
        sa.PrimaryKeyConstraint("run_id", "join_request_id", name="pk_join_requests"),
        sa.UniqueConstraint("run_id", "join_request_seq", name="uq_join_requests_sequence"),
        sa.CheckConstraint("join_request_seq > 0", name="ck_join_requests_sequence"),
        sa.CheckConstraint("status IN ('pending', 'accepted', 'refused', 'expired')", name="ck_join_requests_status"),
        sa.CheckConstraint("requested_world_day BETWEEN 1 AND 7", name="ck_join_requests_requested_day"),
        sa.CheckConstraint("requested_world_minute BETWEEN 0 AND 1439", name="ck_join_requests_requested_minute"),
        sa.CheckConstraint("resolved_world_day IS NULL OR resolved_world_day BETWEEN 1 AND 7", name="ck_join_requests_resolved_day"),
        sa.CheckConstraint("resolved_world_minute IS NULL OR resolved_world_minute BETWEEN 0 AND 1439", name="ck_join_requests_resolved_minute"),
    )
    op.create_table(
        "join_request_approvers",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("join_request_id", sa.String(64), nullable=False),
        sa.Column("approver_actor_id", sa.String(64), nullable=False),
        sa.Column("decision", sa.String(32), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("decided_world_day", sa.SmallInteger(), nullable=True),
        sa.Column("decided_world_minute", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["run_id", "join_request_id"], ["join_requests.run_id", "join_requests.join_request_id"], ondelete="CASCADE", name="fk_join_request_approvers_request"),
        sa.ForeignKeyConstraint(["approver_actor_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_join_request_approvers_actor"),
        sa.PrimaryKeyConstraint("run_id", "join_request_id", "approver_actor_id", name="pk_join_request_approvers"),
        sa.CheckConstraint("decision IN ('pending', 'accept', 'refuse')", name="ck_join_request_approvers_decision"),
        sa.CheckConstraint("decided_world_day IS NULL OR decided_world_day BETWEEN 1 AND 7", name="ck_join_request_approvers_day"),
        sa.CheckConstraint("decided_world_minute IS NULL OR decided_world_minute BETWEEN 0 AND 1439", name="ck_join_request_approvers_minute"),
    )
    op.create_table(
        "conversation_drafts",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("npc_id", sa.String(64), nullable=False),
        sa.Column("draft_version", sa.BigInteger(), nullable=False, server_default=sa.text("1")),
        sa.Column("payload", JSONB, nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("updated_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("updated_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_conversation_drafts_conversation"),
        sa.ForeignKeyConstraint(["npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_conversation_drafts_npc"),
        sa.PrimaryKeyConstraint("run_id", "conversation_id", "npc_id", name="pk_conversation_drafts"),
        sa.CheckConstraint("draft_version > 0", name="ck_conversation_drafts_version"),
        sa.CheckConstraint("updated_world_day BETWEEN 1 AND 7", name="ck_conversation_drafts_day"),
        sa.CheckConstraint("updated_world_minute BETWEEN 0 AND 1439", name="ck_conversation_drafts_minute"),
    )
    op.create_table(
        "consolidations",
        sa.Column("run_id", sa.String(64), nullable=False),
        sa.Column("conversation_id", sa.String(64), nullable=False),
        sa.Column("npc_id", sa.String(64), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default=sa.text("'pending'")),
        sa.Column("reason", sa.String(64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("drafts_committed", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("interaction_recorded", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("updated_world_day", sa.SmallInteger(), nullable=False),
        sa.Column("updated_world_minute", sa.SmallInteger(), nullable=False),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(["run_id", "conversation_id"], ["conversations.run_id", "conversations.conversation_id"], ondelete="CASCADE", name="fk_consolidations_conversation"),
        sa.ForeignKeyConstraint(["npc_id"], ["actors.actor_id"], ondelete="RESTRICT", name="fk_consolidations_npc"),
        sa.PrimaryKeyConstraint("run_id", "conversation_id", "npc_id", name="pk_consolidations"),
        sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed')", name="ck_consolidations_status"),
        sa.CheckConstraint("attempts >= 0", name="ck_consolidations_attempts"),
        sa.CheckConstraint("updated_world_day BETWEEN 1 AND 7", name="ck_consolidations_day"),
        sa.CheckConstraint("updated_world_minute BETWEEN 0 AND 1439", name="ck_consolidations_minute"),
    )


def downgrade() -> None:
    """Remove the first schema in reverse foreign-key order."""

    for table_name in (
        "consolidations",
        "conversation_drafts",
        "join_request_approvers",
        "join_requests",
        "invitations",
        "relationships",
        "goals",
        "conversation_idle_states",
        "messages",
        "segment_participants",
        "conversation_segments",
        "conversation_participants",
        "conversations",
        "topic_candidates",
        "world_event_observers",
        "world_events",
        "command_records",
        "run_events",
        "run_daily_schedules",
        "run_actor_states",
        "chapter_runs",
        "agendas",
        "goal_definitions",
        "topics",
        "npc_profiles",
        "actors",
    ):
        op.drop_table(table_name)
