"""complete_normalized_schema

Revision ID: 34039a40f40d
Revises: 0001_initial_schema
Create Date: 2026-08-19 23:19:39.110583
"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '34039a40f40d'
down_revision: str | None = '0001_initial_schema'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_resolutions',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('agenda_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('player_task_result', sa.String(length=64), nullable=True),
    sa.Column('resolved_world_day', sa.SmallInteger(), nullable=False),
    sa.Column('resolved_world_minute', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("branch IN ('consensus_submitted', 'compromise_submitted', 'no_submission')", name='ck_chapter_resolutions_branch'),
    sa.CheckConstraint('resolved_world_day BETWEEN 1 AND 7', name='ck_chapter_resolutions_day'),
    sa.CheckConstraint('resolved_world_minute BETWEEN 0 AND 1439', name='ck_chapter_resolutions_minute'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_chapter_resolutions_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_chapter_resolutions'))
    )
    op.create_table('run_state_items',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('section', sa.String(length=96), nullable=False),
    sa.Column('item_key', sa.String(length=512), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_run_state_items_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'section', 'item_key', name=op.f('pk_run_state_items'))
    )
    op.create_index('ix_run_state_items_section', 'run_state_items', ['run_id', 'section'], unique=False)
    op.create_table('run_storage_revisions',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('revision >= 0', name='ck_run_storage_revisions_revision'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_run_storage_revisions_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run_storage_revisions'))
    )
    op.create_table('memories',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('owner_npc_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.SmallInteger(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=True),
    sa.Column('segment_id', sa.String(length=64), nullable=True),
    sa.Column('created_world_day', sa.SmallInteger(), nullable=False),
    sa.Column('created_world_minute', sa.SmallInteger(), nullable=False),
    sa.Column('learned_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('learned_world_minute', sa.SmallInteger(), nullable=True),
    sa.Column('occurred_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('occurred_world_minute', sa.SmallInteger(), nullable=True),
    sa.Column('last_recalled_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('last_recalled_world_minute', sa.SmallInteger(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('embedding_dimensions', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("confidence IN ('low', 'medium', 'high')", name='ck_memories_confidence'),
    sa.CheckConstraint("memory_type IN ('event', 'belief', 'commitment', 'relationship_change', 'goal_change', 'reflection')", name='ck_memories_type'),
    sa.CheckConstraint("source IN ('scenario_seed', 'world_event', 'conversation', 'reflection')", name='ck_memories_source'),
    sa.CheckConstraint('(embedding IS NULL AND embedding_dimensions IS NULL AND embedding_model IS NULL) OR (embedding IS NOT NULL AND embedding_dimensions = 384)', name='ck_memories_embedding_metadata'),
    sa.CheckConstraint('created_world_day BETWEEN 1 AND 7', name='ck_memories_created_day'),
    sa.CheckConstraint('created_world_minute BETWEEN 0 AND 1439', name='ck_memories_created_minute'),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name='ck_memories_importance'),
    sa.CheckConstraint('last_recalled_world_day IS NULL OR last_recalled_world_day BETWEEN 1 AND 7', name='ck_memories_recalled_day'),
    sa.CheckConstraint('last_recalled_world_minute IS NULL OR last_recalled_world_minute BETWEEN 0 AND 1439', name='ck_memories_recalled_minute'),
    sa.CheckConstraint('learned_world_day IS NULL OR learned_world_day BETWEEN 1 AND 7', name='ck_memories_learned_day'),
    sa.CheckConstraint('learned_world_minute IS NULL OR learned_world_minute BETWEEN 0 AND 1439', name='ck_memories_learned_minute'),
    sa.CheckConstraint('occurred_world_day IS NULL OR occurred_world_day BETWEEN 1 AND 7', name='ck_memories_occurred_day'),
    sa.CheckConstraint('occurred_world_minute IS NULL OR occurred_world_minute BETWEEN 0 AND 1439', name='ck_memories_occurred_minute'),
    sa.ForeignKeyConstraint(['owner_npc_id'], ['actors.actor_id'], name='fk_memories_owner', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'conversation_id'], ['conversations.run_id', 'conversations.conversation_id'], name='fk_memories_conversation', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'event_id'], ['world_events.run_id', 'world_events.event_id'], name='fk_memories_event', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'segment_id'], ['conversation_segments.run_id', 'conversation_segments.segment_id'], name='fk_memories_segment', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_memories_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'memory_id', name=op.f('pk_memories'))
    )
    op.create_index('ix_memories_embedding_hnsw', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('embedding IS NOT NULL'))
    op.create_index('ix_memories_owner_time', 'memories', ['run_id', 'owner_npc_id', 'created_world_day', 'created_world_minute'], unique=False)
    op.create_index('ix_memories_owner_type', 'memories', ['run_id', 'owner_npc_id', 'memory_type'], unique=False)
    op.create_table('chapter_actor_stances',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('npc_id', sa.String(length=64), nullable=False),
    sa.Column('stance', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('source_message_id', sa.String(length=64), nullable=True),
    sa.Column('source_memory_id', sa.String(length=64), nullable=True),
    sa.Column('effective_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('effective_world_minute', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("stance IN ('unknown', 'support', 'conditional', 'oppose', 'withdrawn')", name='ck_chapter_actor_stances_value'),
    sa.CheckConstraint('effective_world_day IS NULL OR effective_world_day BETWEEN 1 AND 7', name='ck_chapter_actor_stances_day'),
    sa.CheckConstraint('effective_world_minute IS NULL OR effective_world_minute BETWEEN 0 AND 1439', name='ck_chapter_actor_stances_minute'),
    sa.ForeignKeyConstraint(['npc_id'], ['actors.actor_id'], name='fk_chapter_actor_stances_npc', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'source_memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_chapter_actor_stances_memory', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'source_message_id'], ['messages.run_id', 'messages.message_id'], name='fk_chapter_actor_stances_message', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_chapter_actor_stances_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'npc_id', name=op.f('pk_chapter_actor_stances'))
    )
    op.create_table('chapter_agenda_stances',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('agenda_id', sa.String(length=64), nullable=False),
    sa.Column('npc_id', sa.String(length=64), nullable=False),
    sa.Column('stance', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('source_message_id', sa.String(length=64), nullable=True),
    sa.Column('source_memory_id', sa.String(length=64), nullable=True),
    sa.Column('effective_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('effective_world_minute', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("stance IN ('unknown', 'support', 'conditional', 'oppose', 'withdrawn')", name='ck_chapter_agenda_stances_value'),
    sa.CheckConstraint('effective_world_day IS NULL OR effective_world_day BETWEEN 1 AND 7', name='ck_chapter_agenda_stances_day'),
    sa.CheckConstraint('effective_world_minute IS NULL OR effective_world_minute BETWEEN 0 AND 1439', name='ck_chapter_agenda_stances_minute'),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.agenda_id'], name='fk_chapter_agenda_stances_agenda', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['npc_id'], ['actors.actor_id'], name='fk_chapter_agenda_stances_npc', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'source_memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_chapter_agenda_stances_memory', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'source_message_id'], ['messages.run_id', 'messages.message_id'], name='fk_chapter_agenda_stances_message', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_chapter_agenda_stances_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'agenda_id', 'npc_id', name=op.f('pk_chapter_agenda_stances'))
    )
    op.create_index('ix_chapter_agenda_stances_agenda', 'chapter_agenda_stances', ['run_id', 'agenda_id'], unique=False)
    op.create_table('chapter_authorizations',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=32), server_default=sa.text("'none'"), nullable=False),
    sa.Column('source_message_id', sa.String(length=64), nullable=True),
    sa.Column('source_memory_id', sa.String(length=64), nullable=True),
    sa.Column('effective_world_day', sa.SmallInteger(), nullable=True),
    sa.Column('effective_world_minute', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint("value IN ('none', 'approved', 'conditional', 'rejected')", name='ck_chapter_authorizations_value'),
    sa.CheckConstraint('effective_world_day IS NULL OR effective_world_day BETWEEN 1 AND 7', name='ck_chapter_authorizations_day'),
    sa.CheckConstraint('effective_world_minute IS NULL OR effective_world_minute BETWEEN 0 AND 1439', name='ck_chapter_authorizations_minute'),
    sa.ForeignKeyConstraint(['run_id', 'source_memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_chapter_authorizations_memory', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'source_message_id'], ['messages.run_id', 'messages.message_id'], name='fk_chapter_authorizations_message', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['chapter_runs.run_id'], name='fk_chapter_authorizations_run', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_chapter_authorizations'))
    )
    op.create_table('memory_actor_links',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('link_role', sa.String(length=32), server_default=sa.text("'mentioned'"), nullable=False),
    sa.CheckConstraint("link_role IN ('owner', 'mentioned', 'subject', 'source')", name='ck_memory_actor_links_role'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], name='fk_memory_actor_links_actor', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id', 'memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_actor_links_memory', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'memory_id', 'actor_id', name=op.f('pk_memory_actor_links'))
    )
    op.create_index('ix_memory_actor_links_actor', 'memory_actor_links', ['run_id', 'actor_id'], unique=False)
    op.create_table('memory_edges',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('from_memory_id', sa.String(length=64), nullable=False),
    sa.Column('to_memory_id', sa.String(length=64), nullable=False),
    sa.Column('edge_type', sa.String(length=32), nullable=False),
    sa.Column('created_world_day', sa.SmallInteger(), nullable=False),
    sa.Column('created_world_minute', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint("edge_type IN ('SUPPORTS', 'CAUSES', 'CONTRADICTS', 'SUPERSEDES', 'DERIVED_FROM')", name='ck_memory_edges_type'),
    sa.CheckConstraint('created_world_day BETWEEN 1 AND 7', name='ck_memory_edges_day'),
    sa.CheckConstraint('created_world_minute BETWEEN 0 AND 1439', name='ck_memory_edges_minute'),
    sa.CheckConstraint('from_memory_id <> to_memory_id', name='ck_memory_edges_distinct_memories'),
    sa.ForeignKeyConstraint(['run_id', 'from_memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_edges_from_memory', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id', 'to_memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_edges_to_memory', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'from_memory_id', 'to_memory_id', 'edge_type', name=op.f('pk_memory_edges'))
    )
    op.create_index('ix_memory_edges_from', 'memory_edges', ['run_id', 'from_memory_id'], unique=False)
    op.create_index('ix_memory_edges_to', 'memory_edges', ['run_id', 'to_memory_id'], unique=False)
    op.create_table('memory_evidence_messages',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_role', sa.String(length=32), server_default=sa.text("'source'"), nullable=False),
    sa.CheckConstraint("evidence_role IN ('source', 'support', 'contradiction')", name='ck_memory_evidence_messages_role'),
    sa.ForeignKeyConstraint(['run_id', 'memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_evidence_messages_memory', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id', 'message_id'], ['messages.run_id', 'messages.message_id'], name='fk_memory_evidence_messages_message', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'memory_id', 'message_id', name=op.f('pk_memory_evidence_messages'))
    )
    op.create_table('memory_goal_links',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('goal_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.CheckConstraint("role IN ('evidence', 'trigger', 'state_change')", name='ck_memory_goal_links_role'),
    sa.ForeignKeyConstraint(['run_id', 'goal_id'], ['goals.run_id', 'goals.goal_id'], name='fk_memory_goal_links_goal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id', 'memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_goal_links_memory', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'memory_id', 'goal_id', 'role', name=op.f('pk_memory_goal_links'))
    )
    op.create_index('ix_memory_goal_links_goal', 'memory_goal_links', ['run_id', 'goal_id'], unique=False)
    op.create_table('memory_topic_links',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('topic_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['run_id', 'memory_id'], ['memories.run_id', 'memories.memory_id'], name='fk_memory_topic_links_memory', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], name='fk_memory_topic_links_topic', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('run_id', 'memory_id', 'topic_id', name=op.f('pk_memory_topic_links'))
    )
    op.create_index('ix_memory_topic_links_topic', 'memory_topic_links', ['run_id', 'topic_id'], unique=False)
    op.create_index('ix_actors_kind', 'actors', ['kind'], unique=False)
    op.create_index('ix_agendas_chapter', 'agendas', ['chapter_id'], unique=False)
    op.create_index('ix_chapter_runs_chapter_status', 'chapter_runs', ['chapter_id', 'clock_status'], unique=False)
    op.create_index('ix_command_records_created', 'command_records', ['run_id', 'created_at'], unique=False)
    op.create_index('ix_conversation_participants_current', 'conversation_participants', ['run_id', 'conversation_id', 'is_current'], unique=False)
    op.create_index('ix_conversation_segments_conversation', 'conversation_segments', ['run_id', 'conversation_id', 'segment_seq'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['run_id', 'status'], unique=False)
    op.create_index('ix_goal_definitions_owner', 'goal_definitions', ['owner_npc_id'], unique=False)
    op.create_index('ix_goals_owner_status', 'goals', ['run_id', 'owner_npc_id', 'status'], unique=False)
    op.create_index('ix_invitations_pending', 'invitations', ['run_id', 'status'], unique=False)
    op.create_index('ix_join_requests_conversation_status', 'join_requests', ['run_id', 'conversation_id', 'status'], unique=False)
    op.create_index('ix_messages_conversation_time', 'messages', ['run_id', 'conversation_id', 'message_seq'], unique=False)
    op.create_index('ix_messages_segment_time', 'messages', ['run_id', 'segment_id', 'message_seq'], unique=False)
    op.create_index('ix_relationships_from_actor', 'relationships', ['run_id', 'from_actor_id'], unique=False)
    op.create_index('ix_run_actor_states_status', 'run_actor_states', ['run_id', 'external_status'], unique=False)
    op.create_index('ix_run_daily_schedules_day', 'run_daily_schedules', ['run_id', 'world_day', 'slot_order'], unique=False)
    op.create_index('ix_run_events_state_version', 'run_events', ['run_id', 'state_version'], unique=False)
    op.create_index('ix_topic_candidates_status', 'topic_candidates', ['run_id', 'status'], unique=False)
    op.create_index('ix_world_events_time', 'world_events', ['run_id', 'world_day', 'world_minute'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_world_events_time', table_name='world_events')
    op.drop_index('ix_topic_candidates_status', table_name='topic_candidates')
    op.drop_index('ix_run_events_state_version', table_name='run_events')
    op.drop_index('ix_run_daily_schedules_day', table_name='run_daily_schedules')
    op.drop_index('ix_run_actor_states_status', table_name='run_actor_states')
    op.drop_index('ix_relationships_from_actor', table_name='relationships')
    op.drop_index('ix_messages_segment_time', table_name='messages')
    op.drop_index('ix_messages_conversation_time', table_name='messages')
    op.drop_index('ix_join_requests_conversation_status', table_name='join_requests')
    op.drop_index('ix_invitations_pending', table_name='invitations')
    op.drop_index('ix_goals_owner_status', table_name='goals')
    op.drop_index('ix_goal_definitions_owner', table_name='goal_definitions')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index('ix_conversation_segments_conversation', table_name='conversation_segments')
    op.drop_index('ix_conversation_participants_current', table_name='conversation_participants')
    op.drop_index('ix_command_records_created', table_name='command_records')
    op.drop_index('ix_chapter_runs_chapter_status', table_name='chapter_runs')
    op.drop_index('ix_agendas_chapter', table_name='agendas')
    op.drop_index('ix_actors_kind', table_name='actors')
    op.drop_index('ix_memory_topic_links_topic', table_name='memory_topic_links')
    op.drop_table('memory_topic_links')
    op.drop_index('ix_memory_goal_links_goal', table_name='memory_goal_links')
    op.drop_table('memory_goal_links')
    op.drop_table('memory_evidence_messages')
    op.drop_index('ix_memory_edges_to', table_name='memory_edges')
    op.drop_index('ix_memory_edges_from', table_name='memory_edges')
    op.drop_table('memory_edges')
    op.drop_index('ix_memory_actor_links_actor', table_name='memory_actor_links')
    op.drop_table('memory_actor_links')
    op.drop_table('chapter_authorizations')
    op.drop_index('ix_chapter_agenda_stances_agenda', table_name='chapter_agenda_stances')
    op.drop_table('chapter_agenda_stances')
    op.drop_table('chapter_actor_stances')
    op.drop_index('ix_memories_owner_type', table_name='memories')
    op.drop_index('ix_memories_owner_time', table_name='memories')
    op.drop_index('ix_memories_embedding_hnsw', table_name='memories', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('embedding IS NOT NULL'))
    op.drop_table('memories')
    op.drop_table('run_storage_revisions')
    op.drop_index('ix_run_state_items_section', table_name='run_state_items')
    op.drop_table('run_state_items')
    op.drop_table('chapter_resolutions')
    # ### end Alembic commands ###
