"""Database schema package.

Importing this package registers all mapped tables on :class:`Base.metadata`
for Alembic.  It does not create or alter a database by itself.
"""

from .base import Base
from .models import (
    Actor,
    Agenda,
    ChapterActorStance,
    ChapterAgendaStance,
    ChapterAuthorization,
    ChapterResolution,
    ChapterRun,
    CommandRecord,
    Consolidation,
    Conversation,
    ConversationDraft,
    ConversationIdleState,
    ConversationParticipant,
    ConversationSegment,
    Goal,
    GoalDefinition,
    Invitation,
    JoinRequest,
    JoinRequestApprover,
    Memory,
    MemoryActorLink,
    MemoryEdge,
    MemoryEvidenceMessage,
    MemoryGoalLink,
    MemoryTopicLink,
    Message,
    NpcProfile,
    Relationship,
    RunActorState,
    RunDailySchedule,
    RunEvent,
    RunStateItem,
    RunStorageRevision,
    SegmentParticipant,
    Topic,
    TopicCandidate,
    WorldEvent,
    WorldEventObserver,
)

__all__ = [
    "Base",
    "Actor",
    "Agenda",
    "ChapterActorStance",
    "ChapterAgendaStance",
    "ChapterAuthorization",
    "ChapterResolution",
    "ChapterRun",
    "CommandRecord",
    "Consolidation",
    "Conversation",
    "ConversationDraft",
    "ConversationIdleState",
    "ConversationParticipant",
    "ConversationSegment",
    "Goal",
    "GoalDefinition",
    "Invitation",
    "JoinRequest",
    "JoinRequestApprover",
    "Memory",
    "MemoryActorLink",
    "MemoryEdge",
    "MemoryEvidenceMessage",
    "MemoryGoalLink",
    "MemoryTopicLink",
    "Message",
    "NpcProfile",
    "Relationship",
    "RunActorState",
    "RunDailySchedule",
    "RunEvent",
    "RunStateItem",
    "RunStorageRevision",
    "SegmentParticipant",
    "Topic",
    "TopicCandidate",
    "WorldEvent",
    "WorldEventObserver",
]
